### ISSUE TITLE
error on new RNCybersourceDeviceFingerprintPackage()

### ISSUE THREAD

**Issue by pedroenrre** [estuardoeg/react-native-cybersource-device-fingerprint#1]
I'm receving this error when trying to install debug version on Android.

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/home/pedro/Incubatech/peggy/peggy-app/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:72: error: constructor RNCybersourceDeviceFingerprintPackage in class RNCybersourceDeviceFingerprintPackage cannot be applied to given types;
      new RNCybersourceDeviceFingerprintPackage(),
      ^
  required: Application
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (/home/pedro/Incubatech/peggy/peggy-app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:74:39)
    at buildAndRun (/home/pedro/Incubatech/peggy/peggy-app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at then.result (/home/pedro/Incubatech/peggy/peggy-app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

My MainApplication.java is this:

package com.myapp;

import com.estuardoeg.CybersourceDeviceFingerprint.RNCybersourceDeviceFingerprintPackage;

import android.app.Application;
import android.content.Context;

import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.geektime.rnonesignalandroid.ReactNativeOneSignalPackage;
//import org.reactnative.camera.RNCameraPackage;
import com.oblador.vectoricons.VectorIconsPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;
import java.lang.reflect.InvocationTargetException;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {
  private static Application _application;

  private final ReactNativeHost mReactNativeHost =
      new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());

          packages.add(new RNCybersourceDeviceFingerprintPackage(_application));

          return packages;
        }

        @Override
        protected String getJSMainModuleName() {
          return "index";
        }
      };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    _application = this;
    SoLoader.init(this, /* native exopackage */ false);
    initializeFlipper(this); // Remove this line if you don't want Flipper enabled
  }

  
}

**Comment by mauriciomartinscruz** [comment]
Hello, try ignore step 1

NOTE: if you use RN 0.60+ you can autolinking, ignore step 1.

**Comment by pedroenrre** [comment]
For Android, I managed to solve. I had to include on my root a config file (react-native.config.js)

`module.exports = {
  dependencies: {
    'react-native-cybersource-device-fingerprint': {
      platforms: {
        android: null, // disable Android platform, other platforms will still autolink if provided
      },
    },
  },
};`

But, I am having trouble to build on real ios devices. On emulator, it works, but not on real devices. I receive the error message:

`does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64`

**Comment by pedroenrre** [comment]
> Hello, try ignore step 1
> 
> NOTE: if you use RN 0.60+ you can autolinking, ignore step 1.

For Android, I managed to solve. I had to include on my root a config file (react-native.config.js)

`module.exports = {
  dependencies: {
    'react-native-cybersource-device-fingerprint': {
      platforms: {
        android: null, // disable Android platform, other platforms will still autolink if provided
      },
    },
  },
};`

But, I am having trouble to build on real ios devices. On emulator, it works, but not on real devices. I receive the error message:

`does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64`

**Comment by pedroenrre** [comment]
> Hello, try ignore step 1
> 
> NOTE: if you use RN 0.60+ you can autolinking, ignore step 1.

For Android, I managed to solve. I had to include on my root a config file (react-native.config.js)

`module.exports = {
  dependencies: {
    'react-native-cybersource-device-fingerprint': {
      platforms: {
        android: null, // disable Android platform, other platforms will still autolink if provided
      },
    },
  },
};`

But, I am having trouble to build on real ios devices. On emulator, it works, but not on real devices. I receive the error message:

`does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.`

**Comment by Ronicley** [comment]
I have the same issue @pedroenrre

**Comment by lusteck** [comment]
I was having this problem too and I solved it by putting this dependency below in the `react-native.config.js` file and removing the native code (Step 1 android)

  ```
dependencies: {
    'react-native-cybersource-device-fingerprint': {
      platforms: {
        android: {
          packageInstance: 'new RNCybersourceDeviceFingerprintPackage(getApplication())'
        },
      },
    },
  },
```
